name: For Hellow World
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Hello
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: run hello action
        id: hello-action
        run: node index.js
      - name: echo eviroments KEY1
        run: echo $KEY1
      - name: echo eviroments KEY2
        run: echo $KEY2
      - name: echo event head commit message
        run: echo ${{ github.event.head_commit.message }}
